"""Simulation-time schedule of the two planar-move obstacles.

Shared layer. No ROS dependency. The obstacle node and the tests use the same
function, so a recorded (sign, offset, t0) triple reproduces the trajectory.
"""

import math
from typing import Tuple


def obstacle_velocity(axis: str, sign: float, offset: float, speed: float, half_period: float, elapsed: float) -> Tuple[float, float]:
    """Velocity (vx, vy) at ``elapsed`` seconds of simulation time after the
    episode start. The obstacle reverses every ``half_period`` seconds; ``offset``
    shifts the reversal grid; ``sign`` selects the initial direction."""
    if half_period <= 0.0:
        raise ValueError("half_period must be positive")
    segment = math.floor((elapsed + offset) / half_period)
    direction = sign * (-1.0 if segment % 2 else 1.0)
    if axis == "x":
        return direction * speed, 0.0
    if axis == "y":
        return 0.0, direction * speed
    raise ValueError("axis must be 'x' or 'y'")


def _alternating_integral(value: float, half_period: float) -> float:
    """Integral of ``(-1)^floor(t / half_period)`` from zero to ``value``."""
    if value < 0.0 or half_period <= 0.0:
        raise ValueError("value must be non-negative and half_period positive")
    segment = int(math.floor(value / half_period))
    remainder = value - segment * half_period
    completed = half_period if segment % 2 else 0.0
    return completed + (remainder if segment % 2 == 0 else -remainder)


def obstacle_displacement(axis: str, sign: float, offset: float, speed: float,
                          half_period: float, elapsed: float) -> Tuple[float, float]:
    """Exact displacement generated by :func:`obstacle_velocity` over elapsed
    simulation time. This is used both online and by the run validator."""
    if elapsed < 0.0:
        raise ValueError("elapsed must be non-negative")
    integral = sign * speed * (
        _alternating_integral(offset + elapsed, half_period)
        - _alternating_integral(offset, half_period)
    )
    if axis == "x":
        return integral, 0.0
    if axis == "y":
        return 0.0, integral
    raise ValueError("axis must be 'x' or 'y'")
